config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :adventures

get '/bike' => 'adventures#bike'

root "adventures#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
	belongs_to :users

	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :adventures
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :edit, :update, :destroy]



# GET /bike
def bike

  @client = Strava::Api::V3::Client.new(:access_token => "47f86ceb37abbe5fabb10ae20efeb926bcaa43f6")
  @all_bike_adventures = @client.list_athlete_activities

#Below I will go over this whole array to only show activities with Sharon as part of the name.
#ie. check the "name" string to see if a substring matches "Sharon"

#first, create an empty array 
@bike_adventures = []

#then iterate over my original array to find all relevant data and push it to my new array
@all_bike_adventures.each do |aspects|
  @my_string = aspects["name"]
  @my_string.downcase!

  if @my_string.include? "sharon"
      @bike_adventures.push aspects 
  end

end


end


  # GET /adventures
  # GET /adventures.json
  def index

    @adventures = Adventure.all

   #This doesn't work: @all_adventures=@adventures.merge(@bike_adventures)

  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
  end

  # GET /adventures/new
  def new
    @adventure = Adventure.new
  end

  # GET /adventures/1/edit
  def edit
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = Adventure.new(adventure_params)

  #establish relevant API data (see 'bike' method for notes)
      @client = Strava::Api::V3::Client.new(:access_token => "47f86ceb37abbe5fabb10ae20efeb926bcaa43f6")
      @all_bike_adventures = @client.list_athlete_activities

      @bike_adventures = []

      @all_bike_adventures.each do |aspects|
  
        @my_string = aspects["name"]
        @my_string.downcase!

        if @my_string.include? "sharon"
          @bike_adventures.push aspects 
        end

      end


#Seting up a loop which will act as a filter to check against my strava data and import this information into the generic form.

    @bike_adventures.each do |aspects|

#Here I am checking the form data against strava's data using date as a comparison point.
#Have to get the dates in equivalent formats first!

      @match_date = Date.parse(aspects["start_date"])
      @match_date = @match_date.strftime('%a, %d %b %Y')


      if @adventure.activity == "Biking" && @match_date === @adventure.date.strftime('%a, %d %b %Y')
          
          @adventure.title = aspects["name"] 
          @adventure.date = @match_date
          @adventure.distance = aspects["distance"]
          @adventure.total_elevation_gain = aspects["total_elevation_gain"] 
          @adventure.duration = aspects["elapsed_time"]
          @adventure.moving_time = aspects["moving_time"]
          @adventure.location_city = aspects["location_city"]
          @adventure.location_state = aspects["location_state"]
          @adventure.location_country = aspects["location_country"]
        
        @adventure.save
        break
      end
    end


    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render :show, status: :created, location: @adventure }
      else
        format.html { render :new }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adventures/1
  # PATCH/PUT /adventures/1.json
  def update
    respond_to do |format|
      if @adventure.update(adventure_params)
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { render :show, status: :ok, location: @adventure }
      else
        format.html { render :edit }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure.destroy
    respond_to do |format|
      format.html { redirect_to adventures_url, notice: 'Adventure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adventure
      @adventure = Adventure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adventure_params
      params.require(:adventure).permit(:activity, :title, :date, :duration, :moving_time, :distance, :total_elevation_gain, :location_city, :location_state, :location_country, :misc_notes)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adventures/_form.html.erb
<%= form_for(@adventure) do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity %><br>
    <%= f.select :activity, options_for_select(["Biking", "Hiking", "Rock Climbing", "Running"])%>
  </div>

    

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>

  <div class="hidden_fields">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :duration %><br>
      <%= f.text_field :duration %>
    </div>

    <div class="field">
      <%= f.label :moving_time %><br>
      <%= f.text_field :moving_time %>
    </div>

    <div class="field">
      <%= f.label :total_elevation_gain %><br>
      <%= f.text_field :total_elevation_gain %>
    </div>

    <div class="field">
      <%= f.label :location_city %><br>
      <%= f.text_field :location_city %>
    </div>
    
    <div class="field">
      <%= f.label :location_state %><br>
      <%= f.text_field :location_state %>
    </div>
    
    <div class="field">
      <%= f.label :location_country %><br>
      <%= f.text_field :location_country %>
    </div>


    <div class="field">
      <%= f.label :adventure_notes %><br>
      <%= f.text_area :misc_notes %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/bike.html.erb
<h1> Bike Adventures </h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Distance</th>
      <th>Date</th>
      <th>Elevation Gain</th>
      <th>Moving Time</th>
      <th>Total Adventure Time</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="5"></th>
    </tr>
  </thead>
<tbody>

	<% @bike_adventures.each do |aspects| %>
	  <tr>
	  	<td><%= aspects["name"] %></td>
	  	<td><%= aspects["distance"]/1000 %>km</td>
	  	<td><%= aspects["start_date"] %></td>
      <td><%= aspects["total_elevation_gain"] %>m</td>
		  <td><%= aspects["moving_time"]/3600 %>hr</td>
      <td><%= aspects["elapsed_time"]/3600 %>hr</td>
      <td><%= aspects["location_city"] %></td>
      <td><%= aspects["location_state"] %></td>
      <td><%= aspects["location_country"] %></td>
	  </tr>
	<% end %>


</tbody>
</table>


app/views/adventures/edit.html.erb
<h1>Editing adventure</h1>

<%= render 'form' %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<h1>Listing adventures</h1>


<table>
  <thead>
    <tr>
      <th>Activity</th>
      <th>Title</th>
      <th>Date</th>
      <th>Total Adventure Time</th>
      <th>Total Active Time</th>
      <th>Distance</th>
      <th>Elevation Gain</th>
      <th>City</th>
      <th>State</th>
      <th>County</th>
      <th>Adventure Thoughts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adventures.each do |adventure| %>
      <tr>
        <td><%= adventure.activity %></td>
        <td><%= adventure.title %></td>
        <td><%= adventure.date %></td>
        <td><%= adventure.duration %>seconds</td>
        <td><%= adventure.moving_time %>seconds</td>
        <td><%= adventure.distance %>m</td>
        <td><%= adventure.total_elevation_gain %>m</td>
        <td><%= adventure.location_city %></td>
        <td><%= adventure.location_state %></td>
        <td><%= adventure.location_country %></td>
        <td><%= adventure.misc_notes %></td>
        <td><%= link_to 'Show', adventure %></td>
        <td><%= link_to 'Edit', edit_adventure_path(adventure) %></td>
        <td><%= link_to 'Destroy', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adventure', new_adventure_path %>

app/views/adventures/new.html.erb
<h1>New adventure</h1>

<%= render 'form' %>

<%= link_to 'Back', adventures_path %>



<script>
  $('.hidden_fields').hide();
  $('#adventure_activity').change(function(){
    if($(this).val() == "Biking"){
      $('.hidden_fields').hide();
    }else{
      $('.hidden_fields').show();
    }
    
  });
</script>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Activity:</strong>
  <%= @adventure.activity %>
</p>

<p>
  <strong>Date:</strong>
  <%= @adventure.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @adventure.title %>
</p>


<%= link_to 'Edit', edit_adventure_path(@adventure) %> |
<%= link_to 'Back', adventures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<header>
	<div class = "header">
	

	<h1>AdventureSite</h1>
	
	</div>
</header>

<body>

<div class="navigation">
	
	<ul>

		<li><%= link_to "All Adventures!", '/adventures' %></li>
		<li><%= link_to "Bike Adventures!", '/bike' %></li>

 	</ul>

 </div>

<div class="content">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</div>



</body>
</html>